	create database library;
    use library;
    
    CREATE TABLE publisher (
		Publisher_Name VARCHAR(100) PRIMARY KEY NOT NULL,
		Publisher_Address VARCHAR(200) NOT NULL,
		Publisher_Phone VARCHAR(50) NOT NULL
	);


	CREATE TABLE book (
		Book_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
		book_Title VARCHAR(100) NOT NULL,
		Publisher_Name VARCHAR(100) NOT NULL , FOREIGN KEY (Publisher_Name) REFERENCES publisher(Publisher_Name) ON UPDATE CASCADE ON DELETE CASCADE
	);
    
	select * from book;
	CREATE TABLE library_branch (
		Branch_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
		Branch_Name VARCHAR(100) NOT NULL,
		Branch_Address VARCHAR(200) NOT NULL
	);


		CREATE TABLE borrower (
		Card_No INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
		Name VARCHAR(100) NOT NULL,
		Address VARCHAR(200) NOT NULL,
		Phone VARCHAR(50) NOT NULL
	);

	

		CREATE TABLE book_loans (
		LoansID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
		BookID INT NOT NULL, FOREIGN KEY(BookID) REFERENCES book(Book_ID) ON UPDATE CASCADE ON DELETE CASCADE,
		Branch_ID INT NOT NULL, FOREIGN KEY(Branch_ID) REFERENCES library_branch(Branch_ID) ON UPDATE CASCADE ON DELETE CASCADE,
		Card_No INT NOT NULL, FOREIGN KEY(Card_No) REFERENCES borrower(Card_No) ON UPDATE CASCADE ON DELETE CASCADE,
		book_loans_DateOut VARCHAR(50) NOT NULL,
		book_loans_DueDate VARCHAR(50) NOT NULL
	);


	 
		CREATE TABLE book_copies (
		Copies_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
		Book_ID INT NOT NULL , FOREIGN KEY(Book_ID) REFERENCES book(Book_ID) ON UPDATE CASCADE ON DELETE CASCADE,
		Branch_ID INT NOT NULL, FOREIGN KEY(Branch_ID) REFERENCES branch(Branch_ID) ON UPDATE CASCADE ON DELETE CASCADE,
		No_Of_Copies INT NOT NULL
	);



		CREATE TABLE book_authors (
		Author_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
		Book_ID INT NOT NULL, FOREIGN KEY(Book_ID) REFERENCES book(Book_ID) ON UPDATE CASCADE ON DELETE CASCADE,
		Author_Name VARCHAR(50) NOT NULL
	);



		

